$(document).ready(function(){
	$("#three_map2").hide();
	$("#three_map3").hide();
	$("#1_btn").click(function(){
		$("#three_map1").show();
		$("#three_map2").hide();
		$("#three_map3").hide();
	});
	$("#2_btn").click(function(){
		$("#three_map1").hide();
		$("#three_map2").show();
		$("#three_map3").hide();
	});
	$("#3_btn").click(function(){
		$("#three_map1").hide();
		$("#three_map2").hide();
		$("#three_map3").show();
	});
});