$(document).ready(function(){
	$("#maps_present").show();
	$("#maps_nac").hide();
	$("#maps_mf").hide();
	$("#maps_ms").hide();
	$("#1_btn").click(function(){
		$("#maps_present").show();
		$("#maps_nac").hide();
		$("#maps_mf").hide();
		$("#maps_ms").hide();
	});
	$("#2_btn").click(function(){
		$("#maps_present").hide();
		$("#maps_nac").show();
		$("#maps_mf").hide();
		$("#maps_ms").hide();
	});
	$("#3_btn").click(function(){
		$("#maps_present").hide();
		$("#maps_nac").hide();
		$("#maps_mf").show();
		$("#maps_ms").hide();
	});
	$("#4_btn").click(function(){
		$("#maps_present").hide();
		$("#maps_nac").hide();
		$("#maps_mf").hide();
		$("#maps_ms").show();
	});
});